### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-hooks-common#1]
Seems `utils` can be imported from `feathers-hooks-common/lib/utils`, rather than `feathers-hooks-common/utils` as per README.

Not sure if this is an issue with the readme or the implementation, or my system could be just screwing up - but when I look for a util function e.g. `checkContext`, I need to look for as per above, rather than what's documented.

**Comment by eddyystop** [comment]
Thanks for catching that. Documentation has been corrected to `/lib/utils`.
