### ISSUE TITLE
Can I feed the populate hook an id from a separate join table ?

### ISSUE THREAD

**Issue by MidnightP** [feathersjs/feathers-hooks-common#100]
```populate(fieldName: string, { service: ServiceName, field = fieldName })```

I am using postgres and have a many-to-many relation. How can I retrieve an item based on an id in another table? I don't have a service for the relation. 

Can the populate hook do this?

**Comment by eddyystop** [comment]
The signature of your function is for the deprecated version of the populate hook. So, to start, ypu should use the more full featured  new version https://docs.feathersjs.com/v/auk/hooks/common/populate.html

Neither populate hook does a m:m join. However you can write your own custom hook to do it for your table.
