### ISSUE TITLE
Do Code Climate analysis again

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#11]
Code Climate complains about duplicate code even if its in different modules. I found that did not work well for me with unit tests as I want each test to be as obvious as possible. I'll look into how to ignore test files.

**Comment by eddyystop** [comment]
@ekryski say:
@eddyystop you can add a codeclimate.yml file to exclude paths. https://docs.codeclimate.com/docs/excluding-files-and-folders

Tightening up some of rules it uses is on my radar for the other repos as well. Definitely not a huge priority though given most of the repos have a 4.0 GPA.

**Comment by daffl** [comment]
The repositories we set up so far (like https://github.com/feathersjs/feathers-permissions) don't seem to include the test files in Code Climate. Maybe because the config at https://github.com/feathersjs/feathers-permissions/blob/master/.istanbul.yml sets the root?

**Comment by daffl** [comment]
Oh nevermind, I see it in some of the other repos, too. Let's look into if we can ignore the `test/` folder in Code Climate. I totally agree, tests are one of the few places where it is totally fine to repeat yourself.

**Comment by ekryski** [comment]
We might be able to even just ignore certain rules

**Comment by eddyystop** [comment]
Here's info I rec'd earlier this year. I had stopped using CC by then
 because of their tardy support.
--------------------------
Jenna Smith <hello@codeclimate.com>
to me
Hey there-

It was buried at the bottom, so not sure if you saw it in my previous
email, but you do have the option to exclude files/folders on a per-engine
basis. For example, if you just wanted to exclude a certain directory from
our duplication analysis, you can do that as well. That would look
something like this:



I realize now that I probably should have put that above the information
about the global excludes so that you could see it better. Sorry about that!

Does that answer your questions? Or is there anything else I can do to help?
-----------------------

Other links:

In case it's helpful, here's a doc that explains all of this in further
detail: https://docs.codeclimate.com/docs/excluding-files-and-folders.

And here's the section that talks about excluding on a per engine basis:
https://docs.codeclimate.com/docs/excluding-files-and-
folders#section-exclude-paths-for-specific-engines.

Here are the analysis CC can run:
https://docs.codeclimate.com/docs/list-of-engines
----------------------

*Frankly*, what will CC do for us other than run esline and look for
duplicate code? Another reason I stopped using CC was the awkward feeling
of paying for a badge.

This does not mean I'm arguing against using CC. I'm just thinking about
what it does for us rather than for people looking at the repos.

**Comment by eddyystop** [comment]
![image](https://cloud.githubusercontent.com/assets/1553311/19478500/d2459704-9510-11e6-8971-ff201ba5755e.png)

**Comment by eddyystop** [comment]
The analysis of feathers-hooks-common is [here](https://codeclimate.com/repos/5806260512a2bb7803000d7a/issues).

My question is: do you really want me to remove this repetative code?

The only way I remember to allow duplicate snippets is to get from CC a hash of each snippet and put the hashes into the yaml file.

BTW here is my yaml
```
languages:
  JavaScript: true
engines:
  duplication:
    enabled: true
    # need this: Config Error: Unable to run the duplication engine without any languages enabled.
    config:
      languages:
      - javascript
    exclude_paths:
    - "test/"
exclude_paths:
- "lib/"
```

**Comment by eddyystop** [comment]
Ignore This Issue

To ignore this duplication issue modify your .codeclimate.yml file and add 0323a4bda01997a1319c35acadcd8c4b to exclude_fingerprints. An example is shown below.

.codeclimate.yml
engines:
  # ... CONFIG CONTENT ...
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 0323a4bda01997a1319c35acadcd8c4b
# ... CONFIG CONTENT ...
