### ISSUE TITLE
Look into the Babel transpiling issue in a section of populate hook.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#116]
A reminder for eddyystop.

**Comment by daffl** [comment]
What was the offending code again?

**Comment by eddyystop** [comment]
https://github.com/feathersjs/feathers-hooks-common/pull/84
https://github.com/feathersjs/feathers-hooks-common/pull/89

**Comment by daffl** [comment]
I think we can close this in favour of https://github.com/feathersjs/feathers/issues/608
