### ISSUE TITLE
Premature with the populate deprecation warning?

### ISSUE THREAD

**Issue by nathanstaines** [feathersjs/feathers-hooks-common#125]
When following along with the quick start guide in the docs I received the deprecation warning for calling populate(target, options). However, when referring to docs.feathersjs.com I was unable to find more information regarding this?

**Comment by eddyystop** [comment]
You can click the dropdown in the navigation column to access the docs for the Auk branch.

https://docs.feathersjs.com/v/auk/hooks/common/populate.html

**Comment by nathanstaines** [comment]
Thanks @eddyystop. Maybe it'd be worth adding that specific link to the deprecation warning. Or changing the pro tip in the docs to explain things a little more clearly. Or updating the quick start guide to use the new populate hook mentioned in the Auk branch? I'd be happy to make a pull request based on whatever is the preferred, if any?

**Comment by eddyystop** [comment]
The new docs will be out shortly, but, yes, submit a PR for the ProTip.

**Comment by nathanstaines** [comment]
If the new docs are going to be out soon then updating the pro tip probably isn't necessary.

PS. I definitely prefer the approach you're taking with the new [feathers-guide](https://github.com/feathersjs/feathers-guide) ;)

**Comment by eddyystop** [comment]
Good to know. Thanks.
