### ISSUE TITLE
Add array traversal to `pluck` hook

### ISSUE THREAD

**Issue by finkef** [feathersjs/feathers-hooks-common#126]
Currently the `pluck` hook does not traverse nested arrays. This would be useful for database results that contain associated objects.

```js
hook.results = [{
  id: 5,
  users: [{
    id: 1,
    ...someMoreData
  }]
}];

// Currently:
pluck('id', 'users.id')(hook.results) = [{ id: 5 }];

// Expected:
pluck('id', 'users.id')(hook.results) = [{ id: 5, users: [{ id: 1 }] }];
```

**Comment by eddyystop** [comment]
The hooks presently use get and set utility routines for dot notation. Converting (all) the hooks from handling a scalar value to riffling through potential (and someone will eventually want multiple) arrays is non-trivial.

**Comment by eddyystop** [comment]
It very easy to write a pluck hook tailored to particular use cases.

I think the comments about too much "magic" in https://github.com/feathersjs/feathers-hooks-common/issues/142 are also applicable here.

Feel free to reopen if you think this should be reconsidered.
