### ISSUE TITLE
Consolidate setCreatedAt and setUpdatedAt hooks to a more generic hook

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-hooks-common#129]
It's weird to do `setCreatedAt({ fieldName: 'archivedAt' })`. It also doesn't make sense to do 2 hooks that do the same thing. We should consolidate them in to a single `setCurrentDateTime` or `setNow` hook. It would behave pretty much the same but you have to pass at least one field.

```js
{
  before: {
    create: [setNow('createdAt', 'updatedAt')],
    update: [setNow('updatedAt')],
    patch: [setNow('updatedAt')],
    remove: [setNow('archivedAt')]
  }
}
```

**Comment by eddyystop** [comment]
Closed with https://github.com/feathersjs/feathers-hooks-common/pull/181 and will be published with v3.3.0.
