### ISSUE TITLE
include does not do a deep merge with its results

### ISSUE THREAD

**Issue by Morriz** [feathersjs/feathers-hooks-common#132]
instead it uses Object.assign.apply, which [supposedly only does shallow copying](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Deep_Clone).
(see `lib/populate.js:123`)

This screws with the results of the included arrays with complex objects like from mongoose. I suggest something like lodash.merge is used instead.

**Comment by Morriz** [comment]
I say we can set an `options.normalize` function which can be passed in the hooks `populate(...` call:

`return Object.assign(options.normalize ? options.normalize(item) : item, ..._toConsumableArray(children));`

**Comment by eddyystop** [comment]
Forgive my ignorance, but wouldn't this be avoided if `lean: true` was
used? No hook works correctly with Mongoose ORMs.

**Comment by eddyystop** [comment]
There's been no response in 22 days, so I'm closing the issue. Feel free to reopen it with more info.
