### ISSUE TITLE
Discard prevents /auth/local

### ISSUE THREAD

**Issue by Mattchewone** [feathersjs/feathers-hooks-common#139]
### Steps to reproduce

The new discard method is discarding the field(s) for all providers including internal calls.

Running the following code within the user hooks will prevent the user from being able to login. 
```
exports.after = {
  all: [hooks.discard('password')],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};
```

Looking at the difference between the old remove and the new discard method is there is a check on the provider, looks like when the internal method for calling the user the password is not being returned which means this error is occurring:

```
User record in the database is missing a 'password'
```

Which is being hit by this within the auth plugin:

```
        // Check password
        const hash = user[this.options.passwordField];

        if (!hash) {
          return done(new Error(`User record in the database is missing a '${this.options.passwordField}'`));
        }
```
### Expected behavior
Should allow internal use of the field(s) being discarded but prevent the field(s) from being returned to any external calls.

### Actual behavior
The field(s) are being removed from all methods including internal ones.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
`feathers-hooks-common@pre`

**Comment by daffl** [comment]
Yes, it has to be discarded conditionally

```js
hooks.when(hook => hook.params.provider, hooks.discard('password'))
```

**Comment by daffl** [comment]
Further discussion in https://github.com/feathersjs/feathers-authentication/issues/434

**Comment by ekryski** [comment]
Closing as this is resolved.

**Comment by kozzztya** [comment]
@daffl I can't find documentation about `hooks.when`. How to use it?

**Comment by eddyystop** [comment]
`when` is one of the common hooks that comes with Feathers. https://docs.feathersjs.com/api/hooks-common.html#when
