### ISSUE TITLE
Convert some REST values so they work in a query object

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#143]
See https://github.com/BestBuy/api-playground/blob/master/src/hooks/index.js

**Comment by eikaramba** [comment]
i would rather traverse the whole object, as i did in my code in the related issue, because it is unlikely you only want to use it in the root where object.

**Comment by eddyystop** [comment]
I agree.

**Comment by eddyystop** [comment]
I think its best people use the `traverse` hook to normalize their values.
