### ISSUE TITLE
Populate include relations with Sequelize

### ISSUE THREAD

**Issue by jlpellicer** [feathersjs/feathers-hooks-common#149]
I want to output a user with a list of his/her roles, like so:
```
user: {
	name: some name,
	email: some email
	roles: [{
			name: admin
		},
		{
			name: sales
		}
	]
}
```
Short and sweet, right?

My first instinct was to solve it in a traditional api url, like `/users/:user_id/roles`

Due to lack of time, I couldn't do this, so I created a new service, that solved it nicely, using the Sequelize models, but on a different api url (`/user-role/:user_id`, which wasn't well received by the team, btw).
```
//user-role.class.js
<snip>
return User.findOne({
	attributes: ['user_id', ...],
	where: {
		user_id: id,
		status: 'active'
	},
	include: [
		{
			model: sequelize.models.roles,
			attributes: ['name'],
			where: {
				status: 'active'
			}
		}
	]
}
<snip>
``` 
```
//users.model.js
<snip>
associate (models) {
	users.belongsToMany(models.roles, {
		through: models.user_roles,
		foreignKey: 'user_id'
	}),
<snip>
``` 

Now, I returned to try and solve it using `users/:user_id/roles`

After a few tries and some help at the FeathersJS Slack channel, I got this working:

```
// users.service.js
<snip>
app.use('/users/:user_id/roles', createService(options));
app.service('/users/:user_id/roles').before({
	find (hook) {
		hook.params.query.user_id = hook.params.user_id;
	}
});
app.service('/users/:user_id/roles').after({
	find: [
		feathers_hooks.remove('password'),
		feathers_hooks.populate({schema: UserRolesSchema})
	]
});
<snip>
``` 

I've got this schema:
```
const UserRolesSchema = {
	include: [{
		service: 'user-roles',
		parentField: 'user_id',
		childField: 'user_id',
		query: {
			$select: ['role_id']
		},
		include: [{
			service: 'roles',
			parentField: 'role_id',
			childField: 'role_id',
			query: {
				$select: ['name', 'status'],
				status: 'active'
			}
		}]
	}],
};
```
Now, tell me if I'm wrong (or maybe it's as obvious as it seems), but the `schema` used to populate, doesn't know about Sequelize (models or anything), so the `schema` joins tables as I'm requesting, right?

I don't know if there is a workaround for this, because, the list I get using this `schema` is not quite as simple as the one I'm aiming for.
It looks like this:
``` 
{
  "total": 1,
  "limit": 10,
  "skip": 0,
  "data": [
    {
      "user_id": "4eca2bc0-ffb3-11e6-b0c4-6f14ee59651a",
      "name": "some name",
      "email": "somemail@gmail.com",
      "status": "active",
      "status_changed_date": null,
      "created_date": "2017-04-13T22:22:31.101Z",
      "updated_date": "2017-04-13T22:22:31.101Z",
      "_include": [
        "user-roles"
      ],
      "user-roles": [
        {
          "role_id": "3d7f9f70-f000-11e6-bc64-92361f002671",
          "_include": [
            "roles"
          ],
          "roles": {
            "name": "admin",
            "status": "active"
          }
        },
        {
          "role_id": "94ab45e2-f000-11e6-bc64-92361f002671",
          "_include": [
            "roles"
          ],
          "roles": {
            "name": "student",
            "status": "active"
          }
        },
        {
          "role_id": "a3688c7a-f000-11e6-bc64-92361f002671",
          "_include": [
            "roles"
          ],
          "roles": {
            "name": "teacher",
            "status": "active"
          }
        },
        {
          "role_id": "74185015-ec95-4049-9acb-6322b49e9b62",
          "_include": [
            "roles"
          ],
          "roles": []
        }
      ]
    }
  ]
}
``` 

That is not the only problem. See the last role? it's empty. It's empty because the condition in the schema requires a role to be active, and that one is inactive, so the `user`-> `user-role` exists, but not the `user-role` -> `role`.

QUESTION 1: 
Is it possible to solve my data structure using the `populate` hook?

QUESTION 2:
Is it possible to use Sequelize to solve the relations and selections inside, I don't know, a custom hook and have it output exactly what I want?

My package.json (feathers-related):
```
"feathers": "^2.1.1",
"feathers-authentication": "^1.2.2",
"feathers-authentication-jwt": "^0.3.1",
"feathers-authentication-local": "^0.3.4",
"feathers-configuration": "^0.4.1",
"feathers-errors": "^2.6.3",
"feathers-hooks": "^1.8.1",
"feathers-hooks-common": "^2.0.3",
"feathers-rest": "^1.7.2",
"feathers-sequelize": "^1.4.5",
"feathers-socketio": "^1.5.2",
```
Thanks!

**Comment by daffl** [comment]
Apologies if I am missing something (I appreciate the thorough issue description though) but did you see the [documentation for includes via Sequelize](https://docs.feathersjs.com/api/databases/sequelize.html#paramssequelize)? This is as opposed to the populate hook which makes indeed individual requests (which is fine for NoSQL databases like MongoDB but not ideal for SQL databases in which case it should be handled through the ORM).

**Comment by eddyystop** [comment]
You are using some clever techniques with `UserRolesSchema`, injecting
Sequelize feature calls into the schema. However the `populate` hook is
intended to be used with vanilla, cross-database Feathers features, so the
hook results are what they are.

I would recommend, as daffl mentions, that you use native Sequelize
features for the entire population if you are going to be using any
Sequelize features at all.

This repo springs to find as an example:
https://github.com/BestBuy/api-playground/tree/master/src/services

**Comment by jlpellicer** [comment]
Thanks a lot, guys.
I'm looking into this 👍

**Comment by jlpellicer** [comment]
This is what I've got so far:
```
find (hook) {
	console.log('Find Before', hook);
	hook.params.query.user_id = hook.params.user_id;
	hook.params.sequelize = {
		include: [
			{
				model: sequelize.models.roles,
				attributes: ['name'],
				where: {
					status: 'active'
				}
			}
		]
	};
}
});
```
But I get:
`error:  ReferenceError: sequelize is not defined`
I've inspected the entire `hook` object, and it seems to be right, there is no `sequelize` defined.
What am I missing?

**Comment by jlpellicer** [comment]
Figured it out, my bad, I was reading the wrong line, it was inside de `include`, `model: sequelize.models.roles`

Just added: `const sequelize = hook.app.get('sequelizeClient');`

**Comment by daffl** [comment]
Yep, that's it! Noticed it was indeed missing in the example so I added it in https://github.com/feathersjs/feathers-docs/commit/c2aa567fa39fc10a6ea11100ac6e28ad7ef1779f, thanks for digging into that. Can we close this issue?

**Comment by jlpellicer** [comment]
Cool!
Closing, thanks!
