### ISSUE TITLE
[feather request] validateSchema receives ajv instance instead of Ajv constructor

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-hooks-common#154]
The `validateSchema` hook currently receives an `Ajv` constructor as its second parameter and creates a new instance of `ajv` inside: (https://github.com/feathersjs/feathers-hooks-common/blob/master/src/services/validate-schema.js#L11)

```js
const validate = new Ajv(options).compile(schema);
```

But in practice we always need to call the `ajv` instance outside the hook to, say, add new keywords or something, like:

```js
var Ajv = require('ajv');
var ajv = new Ajv;
require('ajv-keywords')(ajv);
```
or

```js
ajv.addKeyword('range', { type: 'number', compile: function (sch, parentSchema) {
  var min = sch[0];
  var max = sch[1];

  return parentSchema.exclusiveRange === true
          ? function (data) { return data > min && data < max; }
          : function (data) { return data >= min && data <= max; }
} });
```

Currently I have not found a way to do this for `validateSchema` hook. So I suggest changing/extending the api a little bit, allowing passing an `ajv` instance, instead of the constructor, into the hook function, so we can do the `addKeyword` thing before pass it into the hook.. For backward compatibility,  **the second parameter could be either an instance or a constructor**, something like this:

```js
export default function (schema, ajv, options = { allErrors: true }) {
  const addNewError = options.addNewError || addNewErrorDflt;
  delete options.addNewError;
  if (typeof avj.addKeyword !== 'function') ajv = new ajv(options); // Any better way to tell instance from constructor?
  const validate = ajv.compile(schema); 
  ...
```

**Comment by eddyystop** [comment]
Makes sense.

**Comment by beeplin** [comment]
So do you guys have any better way to tell if the passed-in parameter is an `Ajv` constructor or an `ajv` instance? I could submit a PR for this.

**Comment by eddyystop** [comment]
Not sure but could `instanceof` be used?

**Comment by beeplin** [comment]
cannot use `instanceof` coz if passing in an instance `ajv`, the hook function does not have the constructor `Ajv` so cannot write it as `ajv instanceof Ajv`.

**Comment by eddyystop** [comment]
Fixed with https://github.com/feathersjs/feathers-hooks-common/pull/155. Thanks!

**Comment by eddyystop** [comment]
@beeplin, do you have the time to

update the validateSchema test?
update the its docs in feathers-docs?

**Comment by eddyystop** [comment]
@beeplin. Ajv 5.0.0 is out:

"Ajv version 5.0.0 that supports draft-06 is released. It is likely to require either migrating your schemas or updating your code (to continue using draft-04 and v5 schemas)."

How would 5.0.0 affect you?

**Comment by beeplin** [comment]
I am not familiar with the test stuff but I can do the docs.

**Comment by beeplin** [comment]
I am using ajv 5 and it is all fine

**Comment by beeplin** [comment]
@eddyystop sorry I was kept busy in the past week. Just done the docs and the test. Please check. :)

**Comment by eddyystop** [comment]
Already merged. Thanks!

**Comment by beeplin** [comment]
I would like to close this issue if there is nothing else to do on it. Is it ready to publish a new npm version?

**Comment by eddyystop** [comment]
I'm getting github rate limiting errors trying to publish. Looking into it.

**Comment by eddyystop** [comment]
Pushed as v3.2.0

**Comment by eddyystop** [comment]
@beeplin could you look at https://github.com/feathersjs/feathers-hooks-common/issues/209 ?
