### ISSUE TITLE
Distinct Search hook

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#16]
/*
- Distinct Search - can only be 1 distinct at a time
- \- allows you to URI query like: books?$distinct=author
- ============================================================
  */
  https://github.com/feathersjs/feathers-rest/issues/76#issuecomment-254028560

**Comment by MarcGodard** [comment]
Has this been added?

**Comment by eddyystop** [comment]
I believe that hook is specific to RethinkDB. The common hooks don't tend to have hooks which work for specific DBs. (There is one MongoDB exception tho.)

**Comment by eddyystop** [comment]
I posted this issue as a note to myself.

**Comment by MarcGodard** [comment]
@eddyystop Oh I know I followed it here. Where is the search hook for mongo that you mentioned?

I have been trying to make one, but having trouble.

**Comment by eddyystop** [comment]
The only DB specific hook we have is https://feathers-plus.github.io/v1/feathers-hooks-common/index.html#mongokeys

**Comment by mrfrase3** [comment]
I recently came across this and the old issue and thought I might write an implementation that is more "modernised" and "secured" in case anyone comes across this and wants it. I also added pagination support.

https://gist.github.com/mrfrase3/6f51fb00205a97b44c2ed90b9202a419
