### ISSUE TITLE
Soft delete doubles calls for service.get

### ISSUE THREAD

**Issue by NikitaVlaznev** [feathersjs/feathers-hooks-common#161]
If you have a users service covered with softDelete hook, then there will be 2 users.get calls for every request to it and to eny other service, that requires a populated user, e.g. services that are covered with restrictToRoles.

Since users.get most likely is fetching data from the database it is expensive, because database ops usually are the most expensive operations in request handling code.

It have a significant impact on performance in high load projects.

Second call appears when softDelete hook is calling service.get while already processing service.get request, to check whether the resource is deleted or not. But after this check we have a complete result already, this result was processed by all succeeding hooks, so we do not need to call service.get second time.

The code points:

    case 'get':
      return throwIfItemDeleted(hook.id)
        .then((data) => {

    ...

    function throwIfItemDeleted (id) {
      return service.get(id, { query: { $disableSoftDelete: true } })
        .then(data => {

**Comment by NikitaVlaznev** [comment]
Here is the PR for that: https://github.com/feathersjs/feathers-hooks-common/pull/160.

**Comment by eddyystop** [comment]
Discussion moved to that PR.
