### ISSUE TITLE
Get user is called 4 times in main usage case instead of 1

### ISSUE THREAD

**Issue by NikitaVlaznev** [feathersjs/feathers-hooks-common#164]
One of the main cases is when you have "users" service, with "authenticate" and "softDelete" hooks on.
In the current released version users.get request will be processed like so:

```
1. externall client calls (1)users.get.
  2. authentication hook starts for (1)users.get.
  3. authentication hook calls (2)users.get (inside feathers jwt verifier).
    4. authentication is skipped for (2)users.get, because !hook.params.provider.
    5. softDelete hook starts for (2)users.get.
      6. softDelete hook calls (3)users.get.
      7. authentication hook is skipped for (3)users.get because !hook.params.provider.
      8. softDelete hook is skipped for (3)users.get because hook.params.query.$disableSoftDelete.
      9. (3)users.get is finished.
    10. softDelete hook for (2)users.get finished.
  11. authenctication hook for (1)user.get finished.
  12. softDelete hook starts for (1)users.get
  13. softDelete hook calls (4)users.get
    14. authentication hook is skipped for (4)users.get because !hook.params.provider.
    15. softDelete hook is skipped for (4)users.get because hook.params.query.$disableSoftDelete.
  16. softDelete hook for (1)users.get finished.
  17. authentication hook for (1)users.get finished.
18. external (1)users.get finished.
```

There is a PR #160, that fixes softDelete double calls, but it is not released yet and the fix is not ideal (see #163).

After #160 fix will be applied, there still will be 2 calls, one from authenticate and one from softDelete.

It would be great to fix that, i can assist if anyone will provide a few advices.

**Comment by eddyystop** [comment]
Its relatively uncommon for users to log on. Why should we optimize that case down to one 'get`?

Such optimizations can produce unintended consequences, such as the one from https://github.com/feathersjs/feathers-hooks-common/pull/160 recently.

**Comment by NikitaVlaznev** [comment]
There is a user.get request to obtain self info on every private page render request, is't it a common practice with feathers?

If, for example, there is a user email, status, balance, and other stuff displayed on every page, what other options do i have to get all the required data except calling users.get?

**Comment by marshallswain** [comment]
```
6. softDelete hook calls (3)users.get.
```

Why is `softDelete` calling users.get?  Is this happening implicitly in the auth middleware?

**Comment by eddyystop** [comment]
@marshall, softDelete needs to do a get to see if a record logically exists before doing an update, patch or remove. (A softDelete get now issues 1 get call, where before it did 2.)

NikitaVlaznev says "In my case, this issue multiplies by 4 the process time of the most frequent request." which confuses me. Could you look at what he writes as it involves auth?

**Comment by marshallswain** [comment]
Since that other one has been merged, this is down to 2 requests, now, right?  Is it possible for softDelete to not check if a record logically exists?  Otherwise, I don't see this getting any lower than 2.

**Comment by eddyystop** [comment]
@marshall, `{ query: { $disableSoftDelete: true } }` will perform the method call without first checking if the record logically exists.

**Comment by eddyystop** [comment]
I think we can close this as there's been no additional discussion since May 21st.
