### ISSUE TITLE
paramsFromClient should be removed from feathers docs until ready

### ISSUE THREAD

**Issue by jfcieslak** [feathersjs/feathers-hooks-common#179]
### Steps to reproduce

paramsFromClient – this common hook is referred to in feathersjs official docs, yet it is not actually ready and working.
Docs should be updated to reflect current state of common hooks.
see: https://docs.feathersjs.com/api/hooks-common.html#paramsfromclient

**Module versions** (especially the part that's not working): 3.2.0

**Comment by eddyystop** [comment]
The docs reflect what currently is in the GitHub repo. This will be published later today as mentioned in the PRs related to V3.3.0.
