### ISSUE TITLE
Support an array of hooks

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#19]
``` javascript
const { iff, isProvider, do } from 'feathers-hooks-common';

service.before({
  create: iff(isProvider('external'), do([hook1, hook2, hook3]),
});
```
- Multiple `iff()` avoided for the same condition.
- `feathers-hook-common` creates a promise chain out of the array using code from `feathers-hooks`.  `feathers-hooks` uses that chain without changes to itself.

Comments @daffl ?

**Comment by daffl** [comment]
That definitely makes sense. That question actually came up before (like How can you run a set of hooks conditionally etc). I think the syntax for `iff(isProvider('external'), hook1, hook2, hook3)` might work best (and should be fairly straightforward with ES6 destructuring).

**Comment by eddyystop** [comment]
The ...rest syntax makes sense. I would still have a `do(hook1, hook2)` internally so its available for other potential uses.

**Comment by bedeoverend** [comment]
+1 for `iff(isProvider('external'), hook1, hook2, hook3, ...)` syntax

**Comment by eddyystop** [comment]
This will be in v2.0.3 to be published Nov 29th.
