### ISSUE TITLE
Setting useInnerPopulate to false causes child schema to populate

### ISSUE THREAD

**Issue by n-j-m** [feathersjs/feathers-hooks-common#218]
### Steps to reproduce

Either set `useInnerPopulate` to `false` or leave it as the default. This will cause child models to populate their schema.  From the documentation, this is the opposite of the desired intent.

It looks like this has been fixed in the source, but hasn't been published to npm yet.

The left is from the lib directory from npm, the right is from the lib directory after compiling the github repo.
![image](https://user-images.githubusercontent.com/411630/27304861-18a74c6a-5505-11e7-964e-d332be59ba6e.png)

Without specifying the `useInnerPopulate` option (leaving it the default of `false`), this caused an infinite loop when I requested an endpoint of a service that runs populate on another service that runs populate on the first service... and so on.  To get around this, I had to specify `useInnerPopulate: true`.

**Comment by eddyystop** [comment]
That problem was fixed in 3.5.1 https://github.com/feathersjs/feathers-hooks-common/pull/206 . The publish script should have automatically transpiled into lib/ when 3.5.1 was published.

Anyway 3.5.3 has been published with this lib/ corrected.

Thanks for the catch!
