### ISSUE TITLE
populate: hook.params.user is not populated in child items

### ISSUE THREAD

**Issue by mllrmat** [feathersjs/feathers-hooks-common#220]
populate hook: 

I have a service A which has an after populate hook to load items from service B. Service B has as well an after hook in which some properties should be added depending on the user making the request to service A. Is there any way getting the user object/userId in service B using the populate hook?

**Comment by eddyystop** [comment]
I assume you found the `useInnperPopulate` options. It was introduced due to feedback like yours. So, thanks for any questions!

**Comment by mllrmat** [comment]
Yes, and additionally I discovered that when I call hook.service().get() in a hook I have to set the params myself. 
Small side note: there is a typo in the documentation on `useInnerPopulate` stating userInnerPopulate with an "r"

**Comment by eddyystop** [comment]
Here's some info on setting params https://github.com/feathersjs/feathers/issues/601#issuecomment-310647778

Thanks for the typo catch.

**Comment by eddyystop** [comment]
Typo fixed in https://github.com/feathersjs/feathers-docs/pull/703
