### ISSUE TITLE
Store `deleted` (soft-delete) fields as a date instead of a boolean

### ISSUE THREAD

**Issue by wdmtech** [feathersjs/feathers-hooks-common#228]
Just a suggestion - It would be nice to store this so as to know the time record was soft-deleted.

**Comment by daffl** [comment]
Assuming that you can't modify a deleted item wouldn't that just be the same `updatedAt`?

**Comment by eddyystop** [comment]
https://github.com/feathersjs/feathers-hooks-common/issues/130 makes the same point. however, as daffl points out, i don't know if its worthwhile enough to force existing users to rebuild existing tables.
