### ISSUE TITLE
How to break and return a value to client in before hook

### ISSUE THREAD

**Issue by thREam** [feathersjs/feathers-hooks-common#231]
I want to return a value in before hook, like:
```
service.before({
    create (hook) {
        // const serviceName = '...'
        // const query = { ... }
        return new Promise((resolve, reject) => {
            hook.app.service(serviceName).Model.findOne(query, (err, res) => {
                if (err) {
                    return reject(err)
                }

                // if data has existed, return data
                if (res !== null) {
                    hook.result = res
                }

                return resolve(hook)
            })
        })
    }
})
```

How can I do it?

Thanks

**Comment by eddyystop** [comment]
You can read about that here https://docs.feathersjs.com/guides/step-by-step/basic-feathers/writing-hooks.html#returning-a-result

**Comment by daffl** [comment]
You do it by setting `hook.result` exactly like in the code example that you posted. What exactly is the question/issue?

**Comment by thREam** [comment]
@eddyystop Thanks

**Comment by thREam** [comment]
@daffl Sorry, because of the dependency service's cause, my example code did not working properly. But I did not find it when debugging, now it is normal.

Thank you for your reply.
