### ISSUE TITLE
Populate hook includes data from wrong db service when using a custom query in find

### ISSUE THREAD

**Issue by RobIsHere** [feathersjs/feathers-hooks-common#254]
I made an issue here https://github.com/feathersjs/feathers-knex/issues/117
but that affects also other dbs, because it is an issue of params being simply forwarded.

I think that sequelize is also affected in a similar way with its params.sequelize being forwarded and applied, see:
https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L48

**Comment by eddyystop** [comment]
Am I correct in assuming you've posted this issue here mainly for informational purposes? Though serious, this does not been to be an issue with `populate` itself.

**Comment by RobIsHere** [comment]
I discovered it using populate but you are right it's a more general issue. It's just here to spare other devs some time. And get some attention of someone who has a plan for a fix ;)

**Comment by daffl** [comment]
I'm going to close this one since I think we should try and solve this with the Knex adapter first which is tracked in https://github.com/feathersjs/feathers-knex/issues/117
