### ISSUE TITLE
serialize running twice

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers-hooks-common#255]
For some reason serialize is running twice, so if doing a computed calculation like below, the amount stored in the database is 1000 so 10 should be the computed value, but I'm getting 0.1. 

I've run DEBUG and I'm only seeing one occurance of `mquery find` for the service in question so a bit baffled as to what would be causing it to do this.

Model
```
const productSchema = new Schema(
  {
    special_offer: {
      amount: Number,
      percent: Number,
      start_date: Date,
      end_date: Date
    }
  }
);
```
Serialize Schema
```
module.exports = {
  special_offer: {
    computed: {
      amount: (offer, hook) => offer.amount / 100
    }
  }
};
```

**Comment by eddyystop** [comment]
Put a `debug()` common hook before your serialize hook to see if the app is
running the serialioze hook twice.

**Comment by eddyystop** [comment]
Please put a `debug()` common hook before your serialize hook to see if the app is running the serialioze hook twice.

**Comment by dottodot** [comment]
Turned out to be a stupid mistake by me, I hadn't noticed that I'd still got populate in my `all after hook` as well as my `get after hook`
