### ISSUE TITLE
Should each hook be in their own repository?

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks-common#31]
Recently I've been wondering if the best way to maintain this growing number of hooks would be to migrate each one into their own repository/module (potentially in a separate `feathers-hooks` organization):

- We are already having discussions about major releases related to common hooks. I have the feeling that major versions of this repository could grow very quickly. Updating major versions is a pain for both the maintainers (as I mentioned you have to do more than just make the release e.g. make it public somewhere, document migration, update examples, guides etc.) and users (you have to find out if the version changed, what broke, update your code etc.).
- A breaking major release of `feathers-hooks-common` could be because of an API change of any of the bundled hooks. People will have to go through all the upgrading steps just to find out that they weren't even using that hook.
- There is a chance this repository might become a kitchen sink of hooks that are not related at all (other than they are hooks). Issues can pile up quickly and I think many will be related to the same more complex and most used hooks (e.g. populate).
- It will be easier to split up the documentation into categories since each hook will just be its own module and can be moved around/deprecated/updated independently from each other.
- The only downside I can think of is having to maintain a lot of different modules but we are kind of doing that already. As long as we script repository updates and use the same plugin infrastructure I think we should be good though. In this case we can probably even automate creation by using the GitHub API, initializing a new plugin and copying each hook file and test and publishing it.

_Alternative:_ Another option would be a monorepo structure like [Babel](https://github.com/babel/babel) but I am not too familiar with that (it seems you will have to automate everything in a very similar way).

**Comment by eddyystop** [comment]
There are 26 hooks.
5 are 15-40 LOC (incl comment & blank lines)
15 are 5-15 LOC
3 are 1-5 LOC
The remaining 3 are not large. I lost track of their sizes while counting.
The new populate will be the first large hook.

I wouldn't like the idea of separate repos for each hook as their LOC would be so low.
We will be adding hooks mainly and that's a minor semver change.

I would suggest our biggest problem is organizing the hook documentation, being aware that their number will grow. Some suggestions:

- **The links in the TOC at the top of common.md need to be links to their sections. ** (**)
- Perhaps we should include each hook n ame in that TOC and name it a link to the hook doc.
- Make common.md an intro page and create nested pages for each hook category with docs for those hooks.

(**) I have `* [Deprecations](#deprecations)` and `## <a name="deprecations"></a> Deprecations`. Why doesn't that work?

**Comment by daffl** [comment]
While lines of code should be a consideration I think it is also important to make sure repositories are split into logical pieces. I've seen it more than once for it to turn into big balls of mud otherwise. 

But I guess it is valid to circle back once we think this is becoming a problem. I agree that organizing the documentation should be our first concern. The easiest way I think would be to split it into sub-chapters at the next level (below the "Common hooks" chapter).

**Comment by daffl** [comment]
I'm going to reopen this because I think this can be done more easily as a monorepo using https://github.com/lerna/lerna as suggested in https://github.com/feathersjs/feathers/issues/462. Not sure if it makes sense for other Feathers core repos but I really think it will help organizing common hooks and still keeping each one in their own module.

**Comment by eddyystop** [comment]
Each hook is its own file within feathers-hooks-common
