### ISSUE TITLE
 Sanitize strings to prevent XSS attacks, remove HTML and <script> tags.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#35]
https://mail.google.com/mail/u/0/#inbox/1583aec23c138d0b

**Comment by daffl** [comment]
Can you paste the email here?

**Comment by eddyystop** [comment]
I guess I hadn't had enough coffee.
=============
https://github.com/feathersjs/feathers-docs/issues/134#issuecomment-258700409

@ekryski I've implemented sanitization in my app. While there's lots of ways to do it, I'm using DOMPurify in a before all hook (the sanitize() function below) that I apply to each one of my services.

The hook itself is pretty straightforward:

const jsdom = require('jsdom');
const windowShim = jsdom.jsdom('', {
  features: {
    FetchExternalResources: false,
    ProcessExternalResources: false
  }
}).defaultView;
const DOMPurify = createDOMPurify(windowShim);

/* Sanitizes all string input fields to prevent XSS attacks.
 * Removes all HTML elements and <script> tags.
 */
export function sanitize() {
  return function (hook) {
    const data = _.get(hook, 'data');
    if (_.isObject(data)) {
      Object.keys(data).forEach(function (key) {
        let value = data[key];
        if (_.isString(value)) {
          data[key] = DOMPurify.sanitize(data[key], {ALLOWED_TAGS: []});
        }
      });
    }
    return hook;
  };
}
I'd be happy to add a page to the documentation on the topic of sanitization if you'd like. I haven't done any serialization so I couldn't write about that. Let me know and I can begin work on a PR.

**Comment by eddyystop** [comment]
Read other comments on that issue.

**Comment by ekryski** [comment]
@eddyystop what was the consensus? To just use the hook documented in https://github.com/feathersjs/feathers-hooks-common/issues/35#issuecomment-258911718?

**Comment by eddyystop** [comment]
Issue was raised Apr 13, 2016. One thing maybe was agreed on what that it
was excessive to bring in something like `jsdom` as a hooks dependency. The
discussion that talked about general app security and whether it was in
Feathers' focus or not. Talk of using Helmut to secure HTTP headers.

I closed it as it was going no where.

**Comment by ekryski** [comment]
All good. I agree. If we at some point split hooks into separate modules then sure maybe but for right now I think this is just fine.
