### ISSUE TITLE
utility hook to trim data

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-hooks-common#37]
It would be nice to have a hook that deeply inspects `hook.data` and removes whitespace. Node already has the `String.trim` function, so this would be a fairly straightforward hook to implement.

e.g, before:

```js
hook.data = {
  foo: '    not trimmed    ',
  bar: {
    baz: '   needs  trimming\t\n   '
  },
  bam: 'trimmed'
};
```

and after:

```js
hook.data = {
  foo: 'not trimmed',
  bar: {
    baz: 'needs  trimming'
  },
  bam: 'trimmed'
}
```

**Comment by eddyystop** [comment]
This may be part of the forthcoming serialize hook.

**Comment by eddyystop** [comment]
The `traverse` hook, now waiting for review for Auk, will handle this and much more.

https://github.com/feathersjs/feathers-hooks-common/pull/73
