### ISSUE TITLE
doc some PRs

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#41]
https://github.com/feathersjs/feathers-commons/pull/38

**Comment by daffl** [comment]
What does that mean? I don't think internal utilities need to be documented.

**Comment by eddyystop** [comment]
The repo has some utilities that could be useful to others when they are writing their own hooks. I documented these utilities back in the day.

I agree lodash utilities are better off not documented.

I create issues as I read the firehose of emails sometimes just to think about them later, rather than risk forgeting them.

**Comment by eddyystop** [comment]
Perhaps we should at least mention in the docs that the utils contain some clone lodash utilities. We already have the **Utilities for Hooks** section.

**Comment by eddyystop** [comment]
That issue was for feathers-commons. I misread it as for feathers-hooks-common.
