### ISSUE TITLE
Proposal for permissions in populate++

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#42]
This thread concerns integrating the new feathers-permissions with the new populate++, serialize, etc.

Here are my thoughts.

(1) Populate: Let's take Purchase Requests as an example. Accounting UIs want to show things like invoices and general ledger numbers along with the PR. Purchasing UIs want to show things like receiving slips along with the PR. I would argue that the app decides what type of populate it needs and the hooks have almost no decisions to make.

We can't of course allow a curl command to get whatever it wants, even if another curl was first used to authenticate to a random user. So perhaps populate++ can ensure an Accounting PR populate is at least requested by a user/API/IoT that has Accounting permissions.

So maybe we can have

```javascript
const populations = {
  favorites: {
    // alternative syntax
    permissions: 'acct',
    permissions: ['aaa', 'bbb'],
    permissions: (hook) => true,
    include: {
```

Do we allow `permissions` just at the base record, or do we allow them on every `include`'d table? I would like populate structures to be composable though I'm not sure how effective that would be in practice. `permissions` at every table would be needed.

(2) Serialize: Let's take Payroll as an example, and that we have a populated Employee item. The Payroll Manager is allowed to see the salaries of other department heads, while Payroll Clerks are not. The situation can grow into something more complicated.

I think the server has to decide on the proper serialization and call `hook.serialize(serializers.employee_manager)` with the correct serialization schema from

```javascript
const serializers = {
  employee_manager: { ... },
  employee_clerk: { ... },
```

We can standardize this with something like

```javascript
const serializerPermissions = {
  employee : [
    { permissions: ['payroll-mgr'], serializer: serializers.employee_manager },
    { permissions: 'payroll-clerk', serializer: serializers.employee_clerk },
  ]
}

hooks.serializeWithPermissions((hook) => serializers.employee_manager)
// or
hooks.serializeWithPermissions(serializerPermissions.employee)
```

The serializer decision occurs only at the base record.

(3) If populate and serialize do have different permission needs, then @ekryski 's proposal to separate the hooks was even more smart.

(4) Concerns
- We are allowing only `or`s on the permissions.
- I need to read up on feathers-permissions (sic).

**Comment by eddyystop** [comment]
@ekryski has recommended a syntax that is more complicated but has growth potential.

```javascript
 when: {
      permissions: [
        '*',
        'favourites',
        'favourites:*',
        'favourites:*:*'
      ]
    },
```

**Comment by ekryski** [comment]
Nice work putting this all together @eddyystop. I'm not entirely sure on population but I'm liking where serializing is headed. This is exactly what I was thinking really:

```js
const serializerPermissions = {
  employee : [
    { permissions: ['payroll-mgr'], serializer: serializers.employee_manager },
    { permissions: 'payroll-clerk', serializer: serializers.employee_clerk },
  ]
}
```

I'm thinking population really good be the same. In an medium to large app you might have a bunch of serialization and population "policies" but this is still already so much more scalable than having to create one-off hooks for each entity permission role, group, etc.

I'm publishing feathers-permissions later today with some updated docs.

> We are allowing only ors on the permissions.

I think that is ok in almost most cases. You must have at least 1 of the required permissions. If you require you can create `and` conditions by chaining multiple `checkPermissions` hooks with different configurations.

**Comment by eddyystop** [comment]
@ekryski I'm setting things up so the client can pass `params: { query: { populate: 'a.b.c', serialize: 'd.e.f' }}` for `populate(/*populations.a.b.c*/)` and `serializeWithPermissions(/*serializerPermissions.d.e.f*/)`

The client can now specify the view it wants to get back, which removes boilerplate on the server.

However some control is needed on the server and this is where `permissions` on `populations` comes in.

**Comment by eddyystop** [comment]
I'm thinking a decent permission structure for populate would be `service:schemaName` for populate, and `service.schemaName:role` for serialize.

**Comment by eddyystop** [comment]
https://github.com/eddyystop/feathers-test-populate-etc is where this is being handled.
