### ISSUE TITLE
softDelete undefined.patch issue

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers-hooks-common#44]
I just noticed that in the published npm code, the softDelete is compiled from

```js
return this.patch(hook.id, hook.data, hook.params).then(data => {
```

to

```js
return undefined.patch(hook.id, hook.data, hook.params).then(function (data) {
```

Don't think that's correct. I'll dig around more tomorrow if I get a minute.

**Comment by eddyystop** [comment]
Need to add a proper test.

**Comment by eddyystop** [comment]
I'm writing unit tests. `get` with the above changes returns the soft deleted item.

**Minus**: subsequent code has to check if item is deleted. **Plus**: A softDeleted item can be read and 'undeleted' without hacking with `hooks.iff()`.

I'm inclined to leave it as is. What say you @daffl ?

**Comment by eddyystop** [comment]
softDelete rewritten with tests in v2.0.2
