### ISSUE TITLE
Hooks shouldn't be arrow functions

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks-common#47]
Hooks should not return arrow functions because the context (`this`) is the surrounding context, not the service (which is being set on normal functions).

**Comment by eddyystop** [comment]
I don't think we have an arrow func vs this problem in any hook other than softDelete.

**Comment by daffl** [comment]
It'd be more of a consistency thing (also, plain functions might be a little faster since they don't need to be explicitly bound to another context).

Maybe we should add a `hook.service`? People were confused about what `this` is in a hook before. It'd be pretty easy to add.

**Comment by eddyystop** [comment]
Can we get a hook.serviceRoute also?

**Comment by bedeoverend** [comment]
+1 for `hook.service`. I prefer it over the `this` context so all my hook functions can be arrow functions if needed

**Comment by eddyystop** [comment]
daffl has added `hook.service` and `hook.path` to `feathers-hooks`.
