### ISSUE TITLE
Validate sync function do nothing

### ISSUE THREAD

**Issue by osenvosem** [feathersjs/feathers-hooks-common#49]
From documentation:
> Sync functions return either an error object or null.

The following validation function do nothing.
```js
function messageValidator(values) {
  return new Error('Error message');
}
```

> Promise functions should throw on an error.

Throw on an error or reject with an error object?

**Comment by eddyystop** [comment]
> The following validation function do nothing.

This is an unfortunate misunderstanding about what 'error object' means. In this case it means a typical set of messages for the UI in the format `{ name: 'Already used.', age: 'Must be over 18' }`.

> Throw on an error or reject with an error object?

You can reject with
```javascript
reject(new errors.BadRequest('Values already taken.', { errors: errs }));
```
or throw that error.

**Comment by eddyystop** [comment]
The 'error object' confusion is clarified in the auk release docs.
