### ISSUE TITLE
Validate hook too limited

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers-hooks-common#50]
I'd like to do some async validation and use `app` and some `services` to do so, but the default `validation` hook is only useful for very basic stuff that can be done locally with the data provided.

I started wrapping my validation in a higher order function to pass the `app`, but hooks/index.js that feathers generates are straight up functions.

**Comment by KidkArolis** [comment]
Suggestion, I guess, is to pass `hooks` as the 2nd arg to the `validate` fn in addition to `data`.

**Comment by eddyystop** [comment]
Noted.

We've discussed doing a rethink of validation once the redesigned populate
and serialize hooks are completed.

**Comment by eddyystop** [comment]
https://github.com/feathersjs/feathers-hooks-common/pull/109

This will be available in feathers-hooks-common v3.
