### ISSUE TITLE
"if else" hook

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers-hooks-common#53]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
```js
    common.iff(
      custom.isSuperAdmin(),
      common.pluck('username', 'firstName', 'lastName', 'money'),
      common.pluck('username', 'firstName', 'lastName'),
    )
```
Allow an `else` condition on `iff` hook. Above is not possible. Adding a third parameter for the `else` condition. In some cases, this might give the possibility to chain `iff` hook.
### Actual behavior
Above code is not possible.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 7.2.0

**Operating System**: macOS 10.12

**Comment by eddyystop** [comment]
v2.0.3, just pushed, allows multiple hooks to be run when the predicate is true, e.g. `common.iff(predicate, hook1, hook2, ...)`. Therefore another syntax would be necessary.

**Comment by eddyystop** [comment]
Two enhancements are being pushed in the next few days. The version will be greater than 2.0.3, likely 2.1.3.

iff..else is supported, with multiple hooks for each condition. Nesting is possible.

```javascript
hooks.iff(isServer,
      hookA,
      hooks.iff(isProvider('rest'), hook1, hook2, hook3)
        .else(hook4, hook5),
      hookB
    )
      .else(
        hooks.iff(hook => hook.method === 'create', hook6, hook7)
      )
```

Custom hooks will be able to internally execute multiple hooks.

```javascript
function (hook) {
   ...
   return hooks.combine(hook1, hook2, ...).call(this, currentHook)
     .then(hook => { ... });
 }
```
