### ISSUE TITLE
Improve setByDot

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#58]
```javascript
function betterSetByDot(item, key, value, ifDelete) {
  if (!key.contains(',')) {
    item[key] = value;
    if (value === undefined && ifDelete) {
      delete item[key];
    }
    return;
  }
  
  setByDot(item, key, value, ifDelete);
}
```

and then update serialize

**Comment by daffl** [comment]
Should we investigate using Lodash [_.set](https://lodash.com/docs#set) and probably [_.get](https://lodash.com/docs#get)? I bet they already went through all the pain and edge cases of dot separated key names and we have docs we can refer to.

**Comment by eddyystop** [comment]
I looked at them originally and they looked heavy with calls between
functions.

I have no problem switching but right now I'm interested in some things
that might get us more milage.

**Comment by eddyystop** [comment]
This was basically a note to myself to improve `setByDot` in feathers-hooks-common. That has been done in https://github.com/feathersjs/feathers-hooks-common/pull/59.

Should I close this?
