### ISSUE TITLE
Add defer Hook

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-hooks-common#67]
Essentially it would take a hook function, and run it outside of the rest of the hooks - so that if an error occurs, it doesn't break the request, or if it will potentially take a long time it won't cause lags. Where I've used something like this is for analytics or low priority notifications.

Obviously you could just bake the functionality directly into the hook, but if you're consuming 3rd party hooks, or have a hook you sometimes want to depend on, that wouldn't work.

Is this common enough to be bundled into `hooks-common` / is there a pattern like this already for feathers?

I'm thinking something like this:

```javascript
function defer(handler) {
  return function(hook) {
    setImmediate(() => handler.call(this, hook));
    return hook;
  }
}

app.service('users').after({
  create: [ defer(notify('User Created')) ]
});
```

Happy to make a PR

**Comment by eddyystop** [comment]
I'd like @daffl to comment on this technically.

**Comment by bedeoverend** [comment]
Looking back at this - I wonder if this would be an anti-pattern, and instead hooks that need to operate like this should instead attach to resource events e.g. `app.on('user:created')`? I'm not sure...there is also the benefit of being able to reuse hooks, rather than transform them to use events.

**Comment by eddyystop** [comment]
Thanks for this comment.

Work is being done on hooks for event filters and permissions. We'll address this particular issue when that's stabilized.

**Comment by eddyystop** [comment]
Why not `setTimeout` such an action, binding it to the scope you want?

**Comment by bedeoverend** [comment]
@eddyystop that's essentially what I've done in the demo code at the top of the function. I could definitely just do that each time, but it's just common enough that I'd want to turn it into a reusable function. I understand though if it's consider out of scope for this repo.

**Comment by eddyystop** [comment]
I'll leave this open.

**Comment by bedeoverend** [comment]
I'll put together a pull request (not much code, and I use it for my own project anyway). That way if you feel it's appropriate, can just merge otherwise close, and the onus is off you guys to do initially implementation

**Comment by eddyystop** [comment]
The repo has been heavily refactored. Wait till v3 has been published. I suggest `defer` is too ambiguous a name.

**Comment by eddyystop** [comment]
Can this be done with a separate Promise.then chain that is not returned?

**Comment by bedeoverend** [comment]
Like:

```
function defer(handler) {
  return (hook) => {
    Promise.resolve().then(handler);
    return hook;
  }
}

app.service('users').after({
  create: [ defer(notify('User Created')) ]
});
```

I don't see why not - unless there's a perf consideration with creating a `Promise` vs running `setImmediate`. Also a `Promise` will set it to run on the next tick, whereas `setImmediate` will set it to run at the start of the next event loop. I'm not familiar enough with the event loop to know how big of a difference that is, but certainly a difference.

In general, I'm having second thoughts as to whether this should be something to include - is it an anti-pattern? Is there a case where this should be used over feathers event system? The only one I can think of is so you can simply re-use hooks, rather than having to rewrite them for event handling.

As for a more specific name - what about, `runAsync` or `onNextTick` or something along those lines?

**Comment by eddyystop** [comment]
The issue with SetImmediate is https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate:

```
Non-standard
This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

This method is not expected to become standard, and is only implemented by recent builds of Internet Explorer and Node.js 0.10+. It meets resistance both from Gecko (Firefox) and Webkit (Google/Apple).
```

I believe `nextTick` is Node-only.

So we can't use either setImmediate or nextTick as hooks can run on the client as well as on the server.

A Promise chain would handle defered async processing with extra code. You'd have to use something like setImmediate or nextTick inside the Promise is the defered processing is all sync. But then we've offloaded that decision onto the developer who knows what platforms the code runs on.

**Comment by bedeoverend** [comment]
Ah sorry, yeah I don't use feathers client side, forgot this should be universally available. Yeah sure, could use `setTimeout(callback, 0)`, but I think a Promise chain would be better; a microtask timing would make more sense I think.

Anyway - definitely happy to run with a Promise chain.

**Comment by eddyystop** [comment]
@bedeoverend I took the liberty of adding your (modified) hook as the first addition to the new `feathers-community-hooks` repo. Feel free to modify it based on your experience.
