### ISSUE TITLE
Set model relations for sequelize

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#69]
Some DBs can specify relationships in their method calls. This would be significantly faster than using the populate hook. So is there a hook that could aid this for such DBs?

Potential approaches:

(1) https://github.com/BestBuy/api-playground/blob/master/src/services/products/hooks/index.js

(2) https://github.com/lionelrudaz/api.wellnow.ch
https://github.com/seyz/jsonapi-serializer

(3) From j214e on slack channel

```javascript
let _app;

/* usage:
  setModelRelations(app, {
    categories:{
      hasMany: {
        products: {foreignKey: 'belongsToCategory'}
      }
    }
  })
*/

export function setModelRelations(app, relations) {
  _app = app;

  for (let service in relations) {
    if (relations.hasOwnProperty(service)) {
      if (relations[service].hasMany) {
        const targets = relations[service].hasMany;

        for(let targetService in targets){
          if(targets.hasOwnProperty(targetService)){
            _hasMany(service, targetService, targets[targetService]);
          }
        }
      }

      if (relations[service].belongsTo) {
        const targets = relations[service].belongsTo;

        for(let targetService in targets){
          if(targets.hasOwnProperty(targetService)){
            _belongsTo(service, targetService, targets[targetService]);
          }
        }
      }
    }
  }
}

function _model(service){
  return _app.service(service).Model
}

function _belongsTo(service, targetService, options){
  _model(service).belongsTo(_model(targetService),options)
}

function _hasMany(service, targetService, options){
  _model(service).hasMany(_model(targetService),options)
}
```

**Comment by sambostock** [comment]
From what I can tell, the pattern of using the populate hook leads to N+1 queries. I take it this would tackle that issue?

**Comment by eddyystop** [comment]
This would do that.

This issue is a reminder to see if there's anything a bit generic we could do in such situations. I would want to avoid publishing hooks for particular DBs.

**Comment by daffl** [comment]
Should we close this? The new generator adds code to set up Sequelize associations in https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/templates/sequelize.js#L19

I don't think there is really anything database independent to do here right?

**Comment by eddyystop** [comment]
ryan.wheale is working toward a hook to populate DBs which themselves support joining records together. The idea is a generic interface that supports say 80% of the use cases, for the most popular DBs.

I'll close this issue for now.
