### ISSUE TITLE
v2.0.3 isn't published on NPM

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-hooks-common#74]
Just installed latest version and it's giving me 2.0.2 - looks like 2.0.3 [hasn't been published onto NPM](https://www.npmjs.com/package/feathers-hooks-common) yet?

**Comment by daffl** [comment]
I just published it.

@eddyystop btw, it will do the whole publishing process (bump version, publish, update changelgo) automatically if you use the `npm run release:<version>` script.

**Comment by bedeoverend** [comment]
@daffl thanks!
