### ISSUE TITLE
Change response code

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#80]
exports.after = {
  all: [],
  find: [function (hook) {
    hook.app.response.statusCode = 418
  }],
...

**Comment by eddyystop** [comment]
This was an idea for a new hook. Bad idea.

**Comment by daffl** [comment]
If anybody is wondering why:

- Services are not supposed to know how they are being accessed [so using the request or response object directly should be avoided](https://docs.feathersjs.com/help/faq.html#how-do-i-access-the-request-object-in-hooks-or-services)
- `hook.app` is a reference to the (only) main app object. This means that in this example, the statusCode for *every* request will be changed (not just the hook method).
