### ISSUE TITLE
New populate support `setByDot` 

### ISSUE THREAD

**Issue by harangue** [feathersjs/feathers-hooks-common#85]
While the new populate hook supports `getByDot` with the parent and child fields, it does not permit a dot string in the `nameAs` field. This would also be helpful to have so that all fields can be populated directly on their `parentField`.

**Comment by eddyystop** [comment]
https://github.com/feathersjs/feathers-hooks-common/pull/105
https://github.com/feathersjs/feathers-hooks-common/pull/106

**Comment by eddyystop** [comment]
This feature will be available in feathers-hooks-common v3.
