### ISSUE TITLE
Populate hook: parentField and childField are confusing

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-hooks-common#86]
If we have a system of categories and subcategories, we have:

```js
/*
Category (parent)
    v
Category (child)
*/

{
  service: 'category',
  nameAs: 'subCategories',
  parentField: 'category_id',
  childField: 'id',
  include: [ ... ],
}

/*
Category (child)
    v
Category (parent)
*/

{
  service: 'category',
  nameAs: 'parentCategories',
  parentField: 'parent_id', // but this field is on the child in this case
  childField: 'id', // but this field is on the parent in this case
  include: [ ... ],
}
```

I think that as for relational databases, like mySQL, you should rename parentField to localField and childField to foreignField.

Which will give:

```js
/*
Category (parent)
    v
Category (child)
*/

{
  service: 'category',
  nameAs: 'subCategories',
  localField: 'category_id',
  foreignField: 'id',
  include: [ ... ],
}

/*
Category (child)
    v
Category (parent)
*/

{
  service: 'category',
  nameAs: 'parentCategories',
  localField: 'parent_id',
  foreignField: 'id',
  include: [ ... ],
}
```

**Comment by marshallswain** [comment]
If we are going that direction, I think I would prefer localKey and foreignKey.

**Comment by bertho-zero** [comment]
I also prefer localKey and foreignKey.

**Comment by eddyystop** [comment]
Eric, David and I had **several days** of discussion before settling on parentField and childField. These were the most clear because you know what comes from the item being joined to and what from the items being joined.

Every other naming convention confused someone on the core team, including names similar to localKey and foreignKey which I proposed.

Also its too late to make such a breaking change even if we wanted to.

**Comment by bertho-zero** [comment]
I really struggle with `child` and `parent`, it does not make sense here.

**Comment by eddyystop** [comment]
The parent is the item that is having other items added to it. The child is
the item that is being included in the parent. I do not understand why this
is confusing.

On Sun, Jan 15, 2017 at 7:07 PM, Kévin Berthommier <notifications@github.com
