### ISSUE TITLE
getByDot throws TypeError if undefined obj is passed as first argument

### ISSUE THREAD

**Issue by jeremybini** [feathersjs/feathers-hooks-common#87]
#### getByDot

The performance improvements that were added to `getByDot` (commit `de3497d`), result in a `TypeError` if a null value is passed as the first argument. Previously, this behavior returned undefined.

#### Expected behavior:
I would expect that passing a null obj as the first argument would return undefined (in the same way that querying for an invalid nested property returns undefined)

`getByDot(nonexistantObj, 'property')` -> `undefined`

#### Actual behavior:

`getByDot(nonexistantObj, 'property')` -> throws `TypeError`

**Comment by eddyystop** [comment]
`getByDot` expects a `{}` object as its param. Passing `null` makes little sense.

I'm sorry, but we cannot remain backward compatible when functions are used in unintended ways.

**Comment by jscottsf** [comment]
Actually, this seems to break populate when a parentField has a path that points to an optional field in the returned data.

**Comment by eddyystop** [comment]
`populate` does not handle optional fields, at least not without some preprocessing of data. I suggest you consider the new `fastJoin` hook. You can likely code it to skip missing forign keys and it can rmake just 10% of the service calls that populate requires.
