### ISSUE TITLE
Use changelog generator

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#9]
Waiting till a Node-based one is generated.
https://github.com/feathersjs/feathers/issues/433

either
https://github.com/rafinskipg/git-changelog, or
https://github.com/conventional-changelog/conventional-changelog-cli

**Comment by eddyystop** [comment]
Closing this until a decision is reached for all repos.

**Comment by daffl** [comment]
I think we should stick with at least the Ruby generator for now so that the changelogs all look the same. When using PRs + issues it works fairly well I think.

**Comment by eddyystop** [comment]
I'll look into installing Rails.

**Comment by daffl** [comment]
I think it just needs Ruby and Gem (the package manager). Maybe http://scoop.sh/ can hep? I can also just make the release for now.
