### ISSUE TITLE
Migration guide for deprecations

### ISSUE THREAD

**Issue by IBwWG** [feathersjs/feathers-hooks-common#91]
Using validateUsingCallback() gives `DEPRECATED Removed next ver. (validateUsingCallback)`.  Thanks, but what now?

**Comment by eddyystop** [comment]
`validate(callbackToPromise(func, count))`

**Comment by IBwWG** [comment]
How does that look for this?

```
[
...,
      hooks.validateUsingCallback(server.signup, { app }),
```

I tried `	  hooks.validate(callbackToPromise(server.signup, 2)),` and `	  hooks.validate(callbackToPromise(server.signup, 2).bind( { app } )),` and other variations, but all I get are errors about app being undefined.

**Comment by IBwWG** [comment]
OK, I think I got it.  I forgot .bind takes `this` first.  So I had to change the function's signature to this:

`  signup: (app, data, cb) => {`

and then I could use this:

`	  hooks.validate(callbackToPromise(server.signup, 2).bind(null,app)),`
