### ISSUE TITLE
Populate hook clobbers pagination total

### ISSUE THREAD

**Issue by buske** [feathersjs/feathers-hooks-common#93]
The `populate` hook currently uses the `replaceItems` helper, which clobbers `hook.result.total`:
https://github.com/feathersjs/feathers-hooks-common/blob/master/test/hooks/utils/getReplaceItems.test.js#L167

As a result, if `populate` is used as a post-find hook, the total number of results is replaced with the number of returned results, making it difficult to have normal pagination on the client. This seems like a significant disruption of a common use case.

I am wrapping the populate hook to counteract this behavior, but it seems like `replaceItems` is being a bit heavy-handed and updating (or not updating) pagination counts should be left to the hook writer.

Here is a representative example:

```javascript
const feathers = require('feathers');
const hooks = require('feathers-hooks')
const commonHooks = require('feathers-hooks-common')
const app = feathers();

app.configure(rest())
app.configure(hooks())
app.use('/users', {
  find(params) {
    return Promise.resolve({
      total: 1,
      limit: 2,
      skip: 0,
      data: [
        { id: 1, username: 'jdoe' }
      ]
    })
  }
})

app.use('/messages', {
  find(params) {
    return Promise.resolve({
      total: 1000,
      limit: 2,
      skip: 0,
      data: [
        { id: 1, body: 'Post 1', userId: 1 },
        { id: 2, body: 'Post 2', userId: 1 },
      ]
    })
  }
});

app.service('messages').find().then(console.log)
/*
{ total: 1000,
  limit: 2,
  skip: 0,
  data:
   [ { id: 1, body: 'Post 1', userId: 1 },
     { id: 2, body: 'Post 2', userId: 1 } ] }
 */

const schema = { include: [
  {
    service: 'users',
    nameAs: 'user',
    parentField: 'userId',
    childField: 'id'
  }
]}

app.service('messages').after({
  find: hooks.populate({ schema })
})

app.service('messages').find().then(console.log)
/*
{ total: 2,
  limit: 2,
  skip: 0,
  data: 
   [ { id: 1,
       body: 'Post 1',
       userId: 1,
       _include: [Object],
       user: [Object] },
     { id: 2,
       body: 'Post 2',
       userId: 1,
       _include: [Object],
       user: [Object] } ] }
*/

```

**Comment by eddyystop** [comment]
This will be fixed in feathers-hooks-common v3. https://github.com/feathersjs/feathers-hooks-common/pull/104

Sorry for the delay. The repos had to undergo a refactoring first.
