### ISSUE TITLE
Option {paginate: false} for populate hook

### ISSUE THREAD

**Issue by anrn** [feathersjs/feathers-hooks-common#95]
Populate hook (I tried it with feathers-sequelize) uses method "find" of an included service with query default params. Is it possible to pass {paginate: false} or maybe other options for catch it in service hooks?

**Comment by eddyystop** [comment]
Couldn't you use the populate `query` or even `select` options for that?

**Comment by anrn** [comment]
I tried, but there are no way to do it right. If you use $select — sequelize get params and change a query. The idea is to have a way for passing options for other hooks in an included service, not for a database interface.

**Comment by eddyystop** [comment]
What if you have
```javascript

// new hook coming soon to feathers-hooks-common

const client = function (...whitelist) {

  return hook => {
    whitelist = typeof whitelist === 'string' ? [whitelist] : whitelist;
    const params = hook.params;

    if (params && params.query && params.query.$client && typeof
params.query.$client === 'object') {
      const client = params.query.$client;

      whitelist.forEach(key => {
        if (key in client) {
          params[key] = client[key];
        }
      });

      delete params.query.$client;
    }

    return hook;
  };
}

```

Then construct something like `{ query: { ..., $client: { a: ..., b: ... }
} }` and your first before hook for the service is
```javascript
module.before({
  all: client('a', 'b')
});
```

That would make `hook.params.a` and `hook.params.b` available to the
following hooks.

**Comment by eddyystop** [comment]
You can set the populate `query` option to `{$client: { paginate: false } }` for a service, along with having
`module.before({
  all: client('a', 'b')
});`
for that service. This will achomplish what you are asking.

**Comment by eddyystop** [comment]
This `paginate` feature is included in feathers-hooks-common v3. https://github.com/feathersjs/feathers-hooks-common/pull/103 .
