### ISSUE TITLE
Disable hook: remove last param being a predicate func.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks-common#98]
Other hooks that had deprecated notices for this option, they have had the option removed.

I would prefer getting confirmation that its safe to do so on `disable`.

**Comment by daffl** [comment]
Before Auk final, should we just get a new major release ready that just completely removes all the deprecations (and warnings)?

**Comment by eddyystop** [comment]
This is the last one left. I would like to drop them but don't know the
ramifications.

**Comment by daffl** [comment]
There should be none if we make it a v3.0.0 - in which case we should also get any other breaking changes in though.

**Comment by eddyystop** [comment]
Do we leave `legacyPopulate` in?

Presently `remove` is a no-op on server calls. We could not do this and
require people to use `when(isProvider('external'), remove())`. But that
might cause a lot of complaints.

**Comment by daffl** [comment]
Do you think so? I would say it's the better way to do it (and pretty obvious what is happening there). By now everybody using the hooks that way should've gotten the deprecation messages right?

**Comment by eddyystop** [comment]
I'm for removing all dated code, having v3, and adding a v2 => v3 migration section to the README, and maybe even the docs.

**Comment by eddyystop** [comment]
We decided this would be too breaking a change.
